feat: add tracer point in plog
XiaoMi/rdsn pull request #993
Opened 2021-12-21 10:18 UTC by levy5307

2021-12-23 02:20 UTC, Shuo-Jia approved these changes

2021-12-23 15:31 UTC, acelyc111 requested changes

2021-12-23 15:31 UTC, acelyc111 commented on src/replica/mutation_log.cpp
> +    if (utils::FLAGS_enable_latency_tracer) {
For these debug/trace info on hot paths, better to add `dsn_unlikely`

2021-12-24 02:25 UTC, hycdong approved these changes

2021-12-24 02:26 UTC, Shuo-Jia approved these changes

2021-12-24 06:21 UTC, merged